import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import { join } from "node:path";
import { getEnabledAgents } from "@updagent/shared";
import type { FeedItem, CollectionHealth } from "@updagent/shared";

export function generateNewsletterContent(
  items: FeedItem[],
  date: string,
  collectedAt: string,
  credentialWarning: boolean,
): string {
  const signalItems = items.filter((item) => item.classification === "SIGNAL");
  const enabledAgents = getEnabledAgents();
  const lines: string[] = [];

  lines.push(`# updagent Newsletter — ${date}`);
  lines.push("");
  lines.push(
    `> Auto-generated · ${signalItems.length} new signal${signalItems.length !== 1 ? "s" : ""} · Collected at ${collectedAt} UTC`,
  );
  lines.push(`> [Full feed](../data/feed.json) · [All newsletters](.)`);

  if (credentialWarning) {
    lines.push("");
    lines.push(
      "> ⚠️ **X data may be incomplete** — Tier 1 credentials degraded for some accounts. Check AUTH_TOKEN + CT0.",
    );
  }

  for (const agent of enabledAgents) {
    const agentSignals = signalItems.filter((item) => item.agentId === agent.id);
    if (agentSignals.length === 0) {
      continue;
    }

    lines.push("");
    lines.push(`## ${agent.name}`);

    const releases = agentSignals.filter((item) => item.source === "github");
    if (releases.length > 0) {
      lines.push("");
      lines.push("### 🚀 Releases");
      for (const item of releases) {
        const timeAgo = relativeTime(item.publishedAt);
        const summary = item.text.split("\n")[0]?.slice(0, 120) ?? "";
        lines.push(
          `- **${item.version ?? item.author}** (${timeAgo}) — ${summary}`,
        );
        lines.push(`  [Release notes →](${item.url})`);
      }
    }

    const xSignals = agentSignals.filter((item) => item.source === "x");
    if (xSignals.length > 0) {
      lines.push("");
      lines.push("### 📡 Team Signals");
      for (const item of xSignals) {
        const timeAgo = relativeTime(item.publishedAt);
        const truncated = item.text.slice(0, 200);
        lines.push(
          `- **@${item.author}** (${timeAgo}): "${truncated}${item.text.length > 200 ? "..." : ""}"`,
        );
        lines.push(`  [View →](${item.url})`);
      }
    }
  }

  lines.push("");
  lines.push("---");
  lines.push(
    "*Generated by [updagent](https://github.com/jyoung105/updagent). Next collection: +6h.*",
  );

  return lines.join("\n");
}

export function shouldGenerateNewsletter(newItems: FeedItem[]): boolean {
  return newItems.some((item) => item.classification === "SIGNAL");
}

export async function appendToNewsletter(
  items: FeedItem[],
  newslettersDir: string,
  health?: CollectionHealth | null,
): Promise<string> {
  await mkdir(newslettersDir, { recursive: true });

  const date = new Date().toISOString().split("T")[0] ?? new Date().toISOString();
  const collectedAt = new Date()
    .toUTCString()
    .split(" ")
    .slice(1, 5)
    .join(" ");
  const filePath = join(newslettersDir, `${date}.md`);
  const newContent = generateNewsletterContent(
    items,
    date,
    collectedAt,
    Boolean(health?.credentialWarning),
  );

  let fileExists = false;
  try {
    await access(filePath);
    fileExists = true;
  } catch {
    fileExists = false;
  }

  if (fileExists) {
    const existing = await readFile(filePath, "utf-8");
    await writeFile(filePath, `${existing}\n---\n\n${newContent}`, "utf-8");
  } else {
    await writeFile(filePath, newContent, "utf-8");
  }

  return filePath;
}

function relativeTime(isoDate: string): string {
  const diffMs = Date.now() - new Date(isoDate).getTime();
  const hours = Math.floor(diffMs / (60 * 60 * 1000));
  if (hours < 1) return "just now";
  if (hours === 1) return "1h ago";
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}
